from sqlalchemy import create_engine, Column, Integer, String, Boolean, Text, ForeignKey, DateTime, Float
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from pgvector.sqlalchemy import Vector
from pydantic import BaseModel
from typing import List, Optional
import os  
from dotenv import load_dotenv
from sqlalchemy.sql import func
load_dotenv()

# SQLAlchemy Setup
Base = declarative_base()

# SQLAlchemy Model for GPC Level
class GPCLevel(Base):
    __tablename__ = "gpc_level"
    
    id = Column(Integer, primary_key=True, index=True)
    level = Column(Integer, index=True)
    code = Column(Integer, index=True)
    title = Column(String)
    full_title = Column(String)
    definition = Column(Text)
    definition_excludes = Column(Text)
    active = Column(Boolean)
    parent_id = Column(Integer, ForeignKey('gpc_level.id'))
    level_3_category = Column(String, index=True)
    level_2_category = Column(String, index=True)
    
    # Relationship for self-referencing hierarchy
    parent = relationship('GPCLevel', remote_side=[id], backref='children')

class Items(Base):
    __tablename__ = "items"
    
    id = Column(Integer, primary_key=True)
    vector = Column(Vector(1536))

class ClassificationLog(Base):
    __tablename__ = "classification_logs"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    source = Column(String, nullable=False, default="Gouge Busters", server_default="Gouge Busters", index=True)
    input_text = Column(Text, nullable=False)
    generated_description = Column(Text, nullable=False)
    predicted_gpc_id = Column(Integer, ForeignKey("gpc_level.id"), nullable=False, index=True)
    predicted_gpc_code = Column(Integer, nullable=False, index=True)
    predicted_title = Column(String, nullable=False)
    predicted_full_title = Column(Text, nullable=False)
    level_2_category = Column(String)
    level_3_category = Column(String)
    definition = Column(Text)
    active = Column(Boolean)
    embedding_model = Column(String, nullable=False)
    description_model = Column(String, nullable=False)
    prompt_version = Column(String, nullable=False)
    taxonomy_version = Column(String, nullable=False)
    similarity_score = Column(Float, nullable=False)
    top_candidate_count = Column(Integer, nullable=False, default=0, server_default="0")

    candidates = relationship(
        "ClassificationCandidate",
        back_populates="classification_log",
        cascade="all, delete-orphan"
    )

class ClassificationCandidate(Base):
    __tablename__ = "classification_candidates"

    id = Column(Integer, primary_key=True, index=True)
    classification_log_id = Column(Integer, ForeignKey("classification_logs.id"), nullable=False, index=True)
    rank = Column(Integer, nullable=False)
    gpc_id = Column(Integer, ForeignKey("gpc_level.id"), nullable=False, index=True)
    gpc_code = Column(Integer, nullable=False, index=True)
    title = Column(String, nullable=False)
    full_title = Column(Text, nullable=False)
    similarity_score = Column(Float, nullable=False)

    classification_log = relationship("ClassificationLog", back_populates="candidates")

# Database connection details
DATABASE_URL = os.getenv('DATABASE_URL')
# SQLalchemy only accepts urls like "postgresql://"
# but heroku will not provide so we have to make it ourselves
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Pydantic Models (Generated by datamodel-codegen)

class Child4(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List

class Child3(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List[Child4]

class Child2(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List[Child3]

class Child1(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List[Child2]

class Child(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List[Child1]

class SchemaItem(BaseModel):
    Level: int
    Code: int
    Title: str
    Definition: str
    DefinitionExcludes: Optional[str]
    Active: bool
    Childs: List[Child]

class Model(BaseModel):
    LanguageCode: str
    DateUtc: str
    Schema: List[SchemaItem]
